### ISSUE TITLE
Please implement VncAuth authentication

### ISSUE THREAD

**Issue by julian-seward1** [whitequark/rust-vnc#1]
Connecting tigervnc's viewer to the server I want to connect to produces this
 CConnection: Using RFB protocol version 3.8
 CConnection: Choosing security type VncAuth(2)

Is "VncAuth(2)" different from "VncAuth" ?  I have no idea.  But anyway, that's
what the server appears to request.

**Comment by whitequark** [comment]
Unfortunately I can't do this because the only Rust implementation of DES is currently broken because of https://github.com/aturon/crossbeam/issues/75.

**Comment by whitequark** [comment]
@julian-seward1 OK, I've split out the binaries from the vnc crate, implemented the plumbing for authentication, and inlined the DES code from the `des-rs` crate so that it doesn't pull in broken crossbeam. Then I've discovered that something in the challenge-response handshake doesn't work correctly, because Xvnc refuses to let me in.

I've spent several hours digging through libvnc and des-rs sources and I have no idea what's wrong with it. I am sorry but by this point I will not spend any more of my time figuring out a completely braindead authentication scheme using a broken algorithm. If you have any idea how to fix it, the `des` branch has code that's supposed to work according to the RFB protocol description.

**Comment by whitequark** [comment]
@julian-seward1 So I've randomly revisited this and, amusingly enough, I am far from the only one having this problem: http://www.catonmat.net/blog/curious-case-of-des-algorithm/. To quote:

> Turns out that the VNC authentication reverses the order of bits in every byte of the password.

I am astounded by the depth of depravity, but I'll implement it now for you.

**Comment by whitequark** [comment]
@julian-seward1 That works! Let me know if you would like any minimal examples to go with your use case, or anything else.

**Comment by whitequark** [comment]
Also published 0.4.0 on crates.io, with the client and proxy split off.
